In [1]:
import numpy as np

a = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]])
a = a.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [2]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [3]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [4]:
a_centered_sp = a_centered[0:, 0] @ a_centered[0:, 1]
cov = a_centered_sp / (len(a_centered[0:, 0]) - 1)
a_centered_sp, cov

(8.0, 2.0)

In [5]:
np_cov = np.cov(a.T)
np_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [6]:
np_cov[0][1]

2.0

In [14]:
import pandas as pd

adict = {'author_id':[1, 2, 3],
        'author_name':['Тургенев', 'Чехов', 'Островский']}

authors = pd.DataFrame(adict)

bdict = {
    'author_id':[1, 1, 1, 2, 2, 3, 3],
    'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price':[450, 300, 350, 500, 450, 370, 290]
    
}

book = pd.DataFrame(bdict)
print(authors)
print(book)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский
   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


In [16]:
authors_price = pd.merge(book, authors, how='inner', on='author_id')
authors_price

author_id            book_title  price author_name
0          1           Отцы и дети    450    Тургенев
1          1                 Рудин    300    Тургенев
2          1     Дворянское гнездо    350    Тургенев
3          2      Толстый и тонкий    500       Чехов
4          2       Дама с собачкой    450       Чехов
5          3                 Гроза    370  Островский
6          3  Таланты и поклонники    290  Островский

In [21]:
top5 = authors_price.sort_values(by='price', ascending=False).head(5)
top5

author_id         book_title  price author_name
3          2   Толстый и тонкий    500       Чехов
0          1        Отцы и дети    450    Тургенев
4          2    Дама с собачкой    450       Чехов
5          3              Гроза    370  Островский
2          1  Дворянское гнездо    350    Тургенев

In [30]:
authors_stat = authors_price.copy()
authors_stat['max_price'] = authors_price['price']
authors_stat['min_price'] = authors_price['price']
authors_stat['avg_price'] = authors_price['price']

authors_stat = authors_stat.groupby('author_name').agg({'max_price':'max','min_price':'min','avg_price':'mean'})
authors_stat


max_price  min_price   avg_price
author_name                                  
Островский         370        290  330.000000
Тургенев           450        300  366.666667
Чехов              500        450  475.000000

In [37]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price


author_id            book_title  price author_name    cover
0          1           Отцы и дети    450    Тургенев  твердая
1          1                 Рудин    300    Тургенев   мягкая
2          1     Дворянское гнездо    350    Тургенев   мягкая
3          2      Толстый и тонкий    500       Чехов  твердая
4          2       Дама с собачкой    450       Чехов  твердая
5          3                 Гроза    370  Островский   мягкая
6          3  Таланты и поклонники    290  Островский   мягкая

In [38]:
book_info = pd.pivot_table(authors_price, values='price', index='author_id', columns='cover', aggfunc=np.sum, fill_value=0)
book_info


cover      мягкая  твердая
author_id                 
1             650      450
2               0      950
3             660        0

In [45]:
pd.to_pickle(book_info, 'book_info.pkl')

book_info2 = pd.read_pickle('book_info.pkl')

print("Проверка методом: ", book_info.equals(book_info2))
print(book_info == book_info2)

Проверка методом:  True
cover      мягкая  твердая
author_id                 
1            True     True
2            True     True
3            True     True
